[project]
name = "arima_time_series_statsmodels_stan"
version = "0.1.0"
description = "Comparing ARIMA time series results from Statsmodels and Stan"
channels = ["conda-forge"]
platforms = ["linux-64"]

[system-requirements]
linux = "5.4.0"

[tasks]

[dependencies]
python = ">=3.12.5,<3.13"
polars = ">=1.6.0,<1.7"
numpy = ">=2.1.0,<2.2"
scipy = ">=1.14.1,<1.15"
statsmodels = ">=0.14.2,<0.15"
matplotlib = ">=3.9.2,<3.10"
scikit-learn = ">=1.5.1,<1.6"
pmdarima = ">=2.0.4,<2.1"
jupyter = ">=1.1.1,<1.2"
nbconvert = ">=7.16.4,<7.17"
jupytext = ">=1.16.4,<1.17"
cmdstanpy = ">=1.2.4,<1.3"
arviz = ">=0.20.0,<0.21"
pyreadr = ">=0.5.2,<0.6"

[pypi-dependencies]
skforecast = ">=0.12.0,<0.14"

[feature.dev.dependencies]
hypothesis = ">=6.111.2,<6.112"
pytest = ">=8.3.3,<8.4"

[environments]
default = { features = ["dev"], solve-group = "prod" }
prod = { features = [], solve-group = "prod" }
